In [14]:
import numpy as np

a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

type(a)

a = np.array(['a', 'b', 'c'])
a

a = np.arange(2,20,2)
a

a = np.arange(8, dtype=np.float64)
a

a[5:]
a[:2]

a.sum()
a.std()
a.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [20]:
# Vectorized mathematical operations
# Scaler multiplacation with list objects leads to a repitition of elements
l = [0., 0.5, 1.5, 3., 5.]
2 * l

# ndarray objects implements a proper scaler multiplication
a
2 * a
a ** 2
2 ** a
a ** a

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [61]:
# Universl functions have reduced performance when not using the math module

np.exp(a)
np.sqrt(a)
np.sqrt(2.5)

import math

math.sqrt(2.5)
# math.sqrt(a)
# math.sqrt() function cannot be appled to ndarray object directly

# %timeit np.sqrt(2.5)
# %timeit math.sqrt(2.5)

# np.sqrt is much slower then math.sqrt

b = np.array([a, a * 2])
b

print(b)

b[0]
b[0 ,2]
b[:, 1]
b.sum()
b.sum(axis=0)
b.sum(axis=1)

c = np.zeros((2,3), dtype='i', order='C')

print(c)

c = np.ones((2,3,4), dtype='i', order='C' )

print(c)

d = np.zeros_like(c, dtype=np.float16, order='C')
print(d)

d = np.ones_like(c, dtype=np.float16, order='C')
print(d)

e = np.empty((2,3,2))
print(e)

g = np.linspace(5, 15, 12)
print(g)

g.size
g.itemsize
g.ndim
g.shape
g.dtype
g.nbytes

def p(value):
    print(value)

g = np.arange(15)
p(g)
p(g.shape)
p(np.shape(g))
p(g.reshape((3,5)))
h = g.reshape(5,3)
p(h)
p(h.T)
p(h.transpose())

p(g)
p(np.resize(g, (3,1)))

p(np.hstack((h, 2 * h)))


[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 0.  2.  4.  6.  8. 10. 12. 14.]]
[[0 0 0]
 [0 0 0]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[ 5.          5.90909091]
  [ 6.81818182  7.72727273]
  [ 8.63636364  9.54545455]]

 [[10.45454545 11.36363636]
  [12.27272727 13.18181818]
  [14.09090909 15.        ]]]
[ 5.          5.90909091  6.81818182  7.72727273  8.63636364  9.54545455
 10.45454545 11.36363636 12.27272727 13.18181818 14.09090909 15.        ]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(15,)
(15,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]
[ 0  1  2  3  4  5  6  7  8  9

In [66]:
# Basic Vectorizataion

np.random.seed(100)
r = np.arange(12).reshape((4,3))
s = np.arange(12).reshape((4,3)) * 0.5

p(r)
p(s)
p(r+s)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]
 [4.5 5.  5.5]]
[[ 0.   1.5  3. ]
 [ 4.5  6.   7.5]
 [ 9.  10.5 12. ]
 [13.5 15.  16.5]]
